config/routes.rb
Store::Application.routes.draw do
  resources :products do 
    resources :variantes
  end

 
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  attr_accessible :name

  validates :name, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  before_save :set_defaults

  belongs_to :category
  has_many :variantes

  

  attr_accessible :active, :description, :name, :price, :category_id, :product_id, :foto
  
  has_attached_file :foto, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  
  validates :name, :category_id, presence: true
  validates :price, :numericality => true
  validates :price, :numericality => { :only_integer => true, :greater_than => 0 }

  def set_defaults
    self.active ||= false
  end
end

app/models/variante.rb
class Variante < ActiveRecord::Base
	belongs_to :product
    attr_accessible :color, :tamano
    validates :color, :tamano, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    
    @product = Product.new active: true
    @categories = Category.all
    #@variante=@product.variante.new

  end

  def create
    @product = Product.new params[:product]
    #@variante=@product.variante.new
    
    if @product.valid?
      @product.save
      #return redirect_to product_variante_path (@product, @variante)
      return redirect_to products_path, notice: "Your product #{@product.name} has been created!"
    end

   @categories = Category.all
   render :new
  end

  def show
    @product = Product.find_by_id params[:id]
  end

  def edit
    @product = Product.find_by_id params[:id]
    @categories = Category.all
  end

  def update
    @product = Product.find_by_id params[:id]

    if @product.update_attributes params[:product]
      return redirect_to products_path, notice: "Your product #{@product.name} has been updated!"
    end

    @categories = Category.all
    render :edit
  end
end

app/controllers/variantes_controller.rb
class VariantesController < ApplicationController
  def index
    @variante = Variante.all
  end

  def new
    @product = Product.find(params[:product_id])
    @variante = @product.variantes.build
   # respond_with(@variante)
  end

  def create
    @product = Product.find(params[:product_id])
    @variante = @product.variantes.build(params[:variante])
    if @variante.valid?
    	@variante.save
    
    return redirect_to  product_variantes_path(@product), notice: "Your variante #{@variante} has been created!"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/variantes_helper.rb
module VariantesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<% if product.errors.any? %>
  <h3>Uppss we have a problem</h3>
<% end %>
<%= form_for product do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <span class='error'><%= product.errors[:name].join(', ') %></span>
  <br/>
  <%= f.label :foto %>
  <%= f.file_field :foto %>
  <span class='error'><%= product.errors[:foto].join(', ') %></span>
  <br/>
  <%= f.label :category_id %>
  <%= collection_select :product, :category_id, categories, :id, :name %>
  <span class='error'><%= product.errors[:category_id].join(', ') %></span>
  <br/>
  <%= f.label :descritpion %>
  <%= f.text_area :description, cols: 30, rows: 5 %>
  <br/>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <span class='error'><%= product.errors[:price].join(', ') %></span>
  <br/>
  <%= f.label :active %>
  <%= f.check_box :active, checked_value: true, unchecked_value: false %>
  <br/>
  <%= f.submit 'Save' %>

<% end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>
<%= render partial: 'form', locals: { product: @product, categories: @categories } %>

app/views/products/index.html.erb
<h1>Products list</h1>
<span><%= flash[:notice] %></span>
<p><%= link_to 'New product', new_product_path %></p>
<ul>
  <% @products.each do |product| %>
    <li id='<%= "product_#{product.id}" %>'>
      <%= product.name %> | <%= link_to 'Show', product %>
      </li>
  <% end %>
</ul>

app/views/products/new.html.erb
<h1>New product</h1>
<%= render partial: 'form', locals: { product: @product, categories: @categories } %>

app/views/products/show.html.erb
<h1 >Product</h1>

<% if @product.nil? %>
  <h3>Product not found</h3>
<% else %>
  <p><%= link_to 'Edit', edit_product_path(@product) %></p>
  <p>
  <span>Name: </span><%= @product.name %>
  </p>
   <p>
  <span>Foto: </span><%= image_tag @product.foto.url(:thumb)%>
  </p>
  <p>
  <span>Category: </span><%= @product.try(:category).try(:name) %>
  </p>
  <p>
  <span>Description: </span><%= @product.description %>
  </p>
  <p>
<% end %>
<%= link_to 'add variante', new_product_variante_path(@product) %>
<br/>
<%= link_to 'show variantes', product_variantes_path(@product) %>
<br/>
<%= link_to 'Back', :back %>

app/views/variantes/index.html.erb
<h1>lista de variantes</h1>
<span><%= flash[:notice] %></span>

<ul>
  <% @variante.each do |variante| %>
    <h4>id: <%=variante.id%> </h4>
    <div id='<%= "product_#{variante.id}" %>'>
      <h4>color</h4>
      <%= variante.color %> 
      <h4>tamano</h4>
      <%= variante.tamano %> 
    </div>
    
  <% end %>
</ul>

app/views/variantes/new.html.erb
<h1>new</h1>
<%= form_for @variante, :url => { :action => "create" } do |f| %>
    <%= f.label :color %>
    <%= f.text_field :color %>
    <br/>
    <%= f.label :tamano %>
    <%= f.text_field :tamano %>
    <br/>
  <%= f.submit "Create" %>
<% end %>

app/views/variantes/show.html.erb
<h1>hola</h1>
<% if var.errors.any? %>
  <h3>Uppss we have a problem</h3>
<% end %>
<%= form_for product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <span class='error'><%= product.errors[:name].join(', ') %></span>
  <br/>
  <%= f.label :category_id %>
  <%= collection_select :product, :category_id, categories, :id, :name %>
  <span class='error'><%= product.errors[:category_id].join(', ') %></span>
  <br/>
  <%= f.label :descritpion %>
  <%= f.text_area :description, cols: 30, rows: 5 %>
  <br/>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <span class='error'><%= product.errors[:price].join(', ') %></span>
  <br/>
  <%= f.label :active %>
  <%= f.check_box :active, checked_value: true, unchecked_value: false %>
  <br/>
  <%= f.submit 'Save' %>
<% end %>